### ISSUE TITLE
input type

### ISSUE THREAD

**Issue by JimenaEB** [scsanchez/html5-form#1]
Fijate en el tipo, el dinero siempre es numérico y puedes añadir que no te metan un 0 o números negativos con min 

https://github.com/scsanchez/html5-form/blob/ad265081fedd92d0856b5650f1a3973e08f75abe/index.html#L36

**Comment by scsanchez** [comment]
Genial! Lo he cambiado a esta forma:

https://github.com/scsanchez/html5-form/blob/b5058209ea39b6b91c7db19ed432af656e939ecc/index.html#L36
