### ISSUE TITLE
From buttons

### ISSUE THREAD

**Issue by JimenaEB** [scsanchez/html5-form#2]
Los formularios tienen unos tipos de botones especiales, buscalos y cambiales el tipo
https://github.com/scsanchez/html5-form/blob/ad265081fedd92d0856b5650f1a3973e08f75abe/index.html#L170

**Comment by scsanchez** [comment]
Los he puesto ahora de tipo "submit"

https://github.com/scsanchez/html5-form/blob/b5058209ea39b6b91c7db19ed432af656e939ecc/index.html#L171
