### ISSUE TITLE
Solo un submit

### ISSUE THREAD

**Issue by JimenaEB** [scsanchez/html5-form#4]
Sólo puede haber un botón de submit, en este caso el Cancel sería de tipo reset. Echale un ojillo en la docu ;)
https://github.com/scsanchez/html5-form/blob/b5058209ea39b6b91c7db19ed432af656e939ecc/index.html#L171

**Comment by scsanchez** [comment]
¡De acuerdo! Lo he cambiado a tipo reset y le daré una ojeada a toda la docu. ¡Gracias!

https://github.com/scsanchez/html5-form/blob/c8d198584c59e6089671fd72f444945a30a982a2/index.html#L171
